server:
  port: 8081
multifile:
  db:
    path: src/main/resources/Invoices
  id:
    path: src/main/resources/CurrentID.txt
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:company
